name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          VITE_CoinImageURI: ${{ secrets.COINIMAGEURI }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Bootstrap Packages
        run: npx lerna bootstrap

      - name: Run Build
        env:
          VITE_CoinImageURI: ${{ secrets.COINIMAGEURI }}
        run: npx lerna run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB3_NFT }}"
          channelId: live
          projectId: web3-nft
