name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          VITE_CoinImageURI: ${{ secrets.COINIMAGEURI }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Bootstrap Packages
        run: npm i

      - name: Run Build
        env:
          VITE_CoinImageURI: ${{ secrets.COINIMAGEURI }}
          VITE_PINATA_KEY: ${{ secrets.VITE_PINATA_KEY }}
          VITE_PINATA_SECRET: ${{ secrets.VITE_PINATA_SECRET }}
          VITE_ALCHEMY_KEY: ${{ secrets.VITE_ALCHEMY_KEY }}
          VITE_ALCHEMY_ETH_MAINNET_API: ${{ secrets.VITE_ALCHEMY_ETH_MAINNET_API }}
          VITE_ALCHEMY_ETH_ROPSTEN_API: ${{ secrets.VITE_ALCHEMY_ETH_ROPSTEN_API }}
          VITE_MORALIS_APPLICATION_ID: ${{ secrets.VITE_MORALIS_APPLICATION_ID }}
          VITE_MORALIS_SERVER_URL: ${{ secrets.VITE_MORALIS_SERVER_URL }}
          VITE_MORALIS_API_KEY: ${{ secrets.VITE_MORALIS_API_KEY }}
          VITE_MORALIS_API_SECRET: ${{ secrets.VITE_MORALIS_API_SECRET }}
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NFT_MARKET_6D945 }}"
          channelId: live
          projectId: nft-market-6d945
